services:
  api:
    container_name: flaskApi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src 
    ports:
      - "5000:5000"
    env_file: ./.env
    depends_on:
      - psql
      - redis
    networks:
      - app-network

  psql:
    container_name: psql
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: ./.env
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: always
    networks:
      - app-network

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    env_file: ./.env
    ports:
      - "5050:80"
    depends_on:
      - psql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge